convert-to-cog:
  description: Convert specified assets into Cloud Optimized GeoTIFFs
  handler: task.handler
  memorySize: 1024
  timeout: 900
  module: tasks/convert-to-cog
  environment:
    GDAL_DATA: /opt/share/gdal
    PROJ_LIB: /opt/share/proj
  layers:
    - arn:aws:lambda:us-west-2:552188055668:layer:geolambda:2
    - arn:aws:lambda:us-west-2:552188055668:layer:geolambda-python:1